"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const User_routes_1 = __importDefault(require("./User.routes"));
const Point_routes_1 = __importDefault(require("./Point.routes"));
const Farm_routes_1 = __importDefault(require("./Farm.routes"));
const Setting_routes_1 = __importDefault(require("./Setting.routes"));
const Task_routes_1 = __importDefault(require("./Task.routes"));
const ExtraTask_routes_1 = __importDefault(require("./ExtraTask.routes"));
const MainRoute = (0, express_1.Router)();
MainRoute.use("/user", User_routes_1.default);
MainRoute.use("/point", Point_routes_1.default);
MainRoute.use("/farm", Farm_routes_1.default);
MainRoute.use("/setting", Setting_routes_1.default);
MainRoute.use("/task", Task_routes_1.default);
MainRoute.use("/extra-task", ExtraTask_routes_1.default);
exports.default = MainRoute;
